#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json

# See https://www.git-town.com/configuration-file for details

interactive = true

[branches]
main = "master"
order = "asc"
unknown-type = "feature"

[create]
new-branch-type = "feature"
share-new-branches = "no"
stash = true

[hosting]
github-connector = "api"

[propose]
breadcrumb = "none"
breadcrumb-direction = "down"

[ship]
delete-tracking-branch = false
ignore-uncommitted = false
strategy = "squash-merge"

[sync]
auto-sync = false
detached = false
feature-strategy = "merge"
perennial-strategy = "ff-only"
prototype-strategy = "merge"
push-branches = true
push-hook = false
tags = true
upstream = true
